import os, sys
BASE = os.path.expanduser("~/Desktop/execpartners-fresh")
def patch(rel, old, new, label, expected_count=1):
    path = os.path.join(BASE, rel)
    with open(path) as f: s = f.read()
    actual = s.count(old)
    if actual == 0: print(f"  [MISS]  {label}"); sys.exit(1)
    if actual != expected_count: print(f"  [COUNT] {label} found {actual}x expected {expected_count}x"); sys.exit(1)
    with open(path, "w") as f: f.write(s.replace(old, new))
    print(f"  [ok]   {label}")
SLUG = "app/en/markets/[slug]/page.tsx"
patch(SLUG,'"Private Banking Recruiter Geneva | Senior RMs, Team Heads & EAMs"','"Private Banking Geneva | 2026 Compensation Benchmarks, Market Intelligence & Senior RM Mandates"',"markets/geneva title")
patch(SLUG,'"Specialist private banking recruiter in Geneva. Senior RMs, Team Heads and EAM coverage specialists placed at Swiss and international private banks. Live mandates, compensation benchmarks and portability analysis."','"Geneva private banking market hub: 2026 compensation benchmarks, FINMA licensing, key banks and EAM ecosystem. Executive Partners places Senior RMs and Team Heads confidentially at Swiss and international platforms."',"markets/geneva description")
patch(SLUG,'"Private Banking Recruiter Geneva | Senior RM Jobs"','"Private Banking Geneva | Compensation Benchmarks & Market Hub"',"markets/geneva OG title")
patch(SLUG,'"Geneva private banking recruitment: UHNW/HNW Senior RMs, Team Heads, EAM coverage. Compensation benchmarks, portability analysis and confidential mandates."','"Geneva private banking: UHNW and HNW compensation data, FINMA licensing, EAM ecosystem and live Senior RM mandates. The Geneva private banking market hub from Executive Partners."',"markets/geneva OG description")
patch(SLUG,'"Private Banking Recruiter Zurich | Senior RM & DACH Wealth Management Search"','"Private Banking Zurich | 2026 DACH Compensation Benchmarks & Market Intelligence"',"markets/zurich title")
patch(SLUG,'"Zurich\'s specialist private banking headhunter. Executive Partners places Senior RMs, Team Heads and DACH-focused bankers at leading Swiss private banks. Compensation benchmarks, FINMA licensing and live mandates."','"Zurich private banking market hub: 2026 DACH compensation benchmarks, FINMA licensing, onshore wealth dynamics and key banks. Executive Partners places Senior RMs and Team Heads at leading Zurich platforms."',"markets/zurich description")
patch(SLUG,'"Private Banking Recruiter Zurich | Senior RM Jobs"','"Private Banking Zurich | DACH Compensation Benchmarks & Market Hub"',"markets/zurich OG title")
patch(SLUG,'"Zurich private banking recruitment: onshore DACH, international UHNW. Senior RM and Team Head mandates at top Swiss platforms."','"Zurich private banking: DACH onshore compensation benchmarks, FINMA licensing, key banks and live Senior RM mandates. The Zurich private banking market hub from Executive Partners."',"markets/zurich OG description")
AGENCY = "app/en/private-banking-recruitment-agency/page.tsx"
patch(AGENCY,'"Private Banking Recruitment Agency in Switzerland | Executive Partners"','"Retained Private Banking Recruitment Agency Switzerland | Executive Partners"',"agency absolute title")
patch(AGENCY,'"Private Banking Recruitment Agency Switzerland | Executive Partners"','"Retained Private Banking Recruitment Agency Switzerland | Executive Partners"',"agency OG+Twitter title",expected_count=2)
patch(AGENCY,'"Executive Partners is a Geneva-based private banking recruitment agency specialising exclusively in senior hires for Swiss and international wealth managers. Senior RMs, Team Heads and Investment Advisors placed across Geneva, Zurich, Dubai, Singapore, Riyadh and London."','"Executive Partners is a Geneva-based retained private banking recruitment agency working exclusively with banks and EAMs on confidential senior mandates. No contingency. No panels. One calibrated shortlist per search."',"agency main description")
patch(AGENCY,'"Geneva-based boutique placing Senior RMs, Team Heads and Investment Advisors across 13 global wealth hubs. Confidential. Senior-level only."','"Geneva-based retained boutique private banking recruitment agency. Senior RMs, Team Heads and Investment Advisors placed across 14 global wealth hubs. Confidential. No contingency. No panels."',"agency OG+Twitter description",expected_count=2)
patch(AGENCY,'<span className="font-semibold text-neutral-100">13 global wealth hubs</span>','<span className="font-semibold text-neutral-100">14 global wealth hubs</span>',"agency body hub count")
patch(AGENCY,'{ n: "13", label: "Global hubs" }','{ n: "14", label: "Global hubs" }',"agency stat card")
patch(AGENCY,'cover all 13 hubs','cover all 14 hubs',"agency hiring managers section")
patch(AGENCY,'"Compensation benchmarks and hiring signals across 13 hubs."','"Compensation benchmarks and hiring signals across 14 hubs."',"agency tools desc")
HEADHUNTER = "app/en/private-banking-headhunter-geneva/page.tsx"
patch(HEADHUNTER,'"Private Banking Headhunter Geneva | Executive Search for Senior RMs & Team Heads"','"Private Banking Headhunter Geneva | Proactive Direct Search for Senior RMs Not Actively in the Market"',"headhunter title")
patch(HEADHUNTER,'"Executive Partners is a Geneva-based private banking headhunter specialising in the recruitment of Senior RMs, Desk Heads and Wealth Managers for Swiss and international banks. 200+ placements, 98% retention."','"Executive Partners is a Geneva-based private banking headhunter that reaches senior bankers who are not actively in the market. Confidential direct approach for Senior RMs, Desk Heads and Team Leaders at Swiss and international banks. 200+ placements, 98% retention."',"headhunter description")
patch(HEADHUNTER,"          Private Banking Headhunter in Geneva","          Private Banking Headhunter: Reaching Senior Bankers Who Are Not in the Market","headhunter H1")
COMPANY = "app/en/private-banking-recruitment-company/page.tsx"
COMPANY_FAQ = "\nconst faqJsonLd = {\n  '@context': 'https://schema.org',\n  '@type': 'FAQPage',\n  mainEntity: [\n    { '@type': 'Question', name: 'What does a private banking recruitment company do?', acceptedAnswer: { '@type': 'Answer', text: 'A private banking recruitment company sources and places senior front-office professionals, primarily Relationship Managers, Team Heads and Investment Advisors, at private banks, EAMs and family offices. A specialist firm like Executive Partners focuses exclusively on private banking and wealth management, with deep knowledge of AUM portability, compensation benchmarks and client-franchise dynamics.' } },\n    { '@type': 'Question', name: 'How does Executive Partners differ from other private banking recruitment companies?', acceptedAnswer: { '@type': 'Answer', text: 'Executive Partners works exclusively on senior private banking mandates. Every candidate is assessed for AUM portability, revenue quality and compliance history before being presented. We operate on a retained or engaged basis, never contingency. Our 98% twelve-month retention rate across 200+ placements reflects that model.' } },\n    { '@type': 'Question', name: 'Which markets does Executive Partners cover?', acceptedAnswer: { '@type': 'Answer', text: 'Executive Partners covers 14 global private banking hubs: Geneva, Zurich, London, Dubai, Singapore, Hong Kong, New York, Miami, Paris, Milan, Madrid, Lisbon, Riyadh and Tel Aviv.' } },\n    { '@type': 'Question', name: 'Do you work with senior bankers who are not actively looking for a new role?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Most senior bankers who engage Executive Partners are not actively searching. They want to understand their AUM portability, assess their market value, and identify which platforms are the best strategic fit. All conversations are fully confidential and carry no obligation.' } },\n  ],\n}\n\n"
patch(COMPANY,'export const metadata: Metadata = {',COMPANY_FAQ + 'export const metadata: Metadata = {',"company faqJsonLd const")
patch(COMPANY,'      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />','      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />\n      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />',"company FAQ script tag")
COMPANY_FAQ_SEC = '      <section className="mb-16 border-t border-current border-opacity-10 pt-12">\n        <h2 className="text-xl font-semibold mb-8">Frequently Asked Questions</h2>\n        <div className="space-y-6">\n          {[\n            { q: "What does a private banking recruitment company do?", a: "A private banking recruitment company sources and places senior front-office professionals, primarily Relationship Managers, Team Heads and Investment Advisors, at private banks, EAMs and family offices. A specialist firm like Executive Partners focuses exclusively on private banking and wealth management, with deep knowledge of AUM portability, compensation benchmarks and client-franchise dynamics." },\n            { q: "How does Executive Partners differ from other private banking recruitment companies?", a: "Executive Partners works exclusively on senior private banking mandates. Every candidate is assessed for AUM portability, revenue quality and compliance history before being presented. We operate on a retained or engaged basis, never contingency. Our 98% twelve-month retention rate across 200+ placements reflects that model." },\n            { q: "Which markets does Executive Partners cover?", a: "Executive Partners covers 14 global private banking hubs: Geneva, Zurich, London, Dubai, Singapore, Hong Kong, New York, Miami, Paris, Milan, Madrid, Lisbon, Riyadh and Tel Aviv." },\n            { q: "Do you work with senior bankers who are not actively looking?", a: "Yes. Most senior bankers who engage Executive Partners are not actively searching. They want to understand their AUM portability, assess their market value, and identify which platforms are the best strategic fit. All conversations are fully confidential and carry no obligation." },\n          ].map(({q, a}) => (\n            <div key={q} className="border-b border-current border-opacity-10 pb-6 last:border-0">\n              <h3 className="font-medium mb-2">{q}</h3>\n              <p className="text-sm opacity-60 leading-relaxed">{a}</p>\n            </div>\n          ))}\n        </div>\n      </section>\n      '
patch(COMPANY,'      <section>\n        <h2 className="text-lg font-semibold mb-4">Related</h2>',COMPANY_FAQ_SEC + '      <section>\n        <h2 className="text-lg font-semibold mb-4">Related</h2>',"company visible FAQ")
patch(COMPANY,'          <li><Link href="/en/private-banking-recruiter-geneva" className="underline underline-offset-2">Private banking recruitment in Geneva</Link></li>\n          <li><Link href="/en/hiring-managers" className="underline underline-offset-2">For hiring managers: brief a mandate</Link></li>\n          <li><Link href="/en/markets" className="underline underline-offset-2">All market hubs</Link></li>\n          <li><Link href="/en/private-banking-recruitment-agency" className="underline underline-offset-2">Private banking recruitment agency</Link></li>','          <li><Link href="/en/private-banking-recruiter-geneva" className="underline underline-offset-2">Private banking recruiter Geneva</Link></li>\n          <li><Link href="/en/private-banking-recruiter-switzerland" className="underline underline-offset-2">Private banking recruiter Switzerland</Link></li>\n          <li><Link href="/en/latam-private-banking-recruiter-geneva" className="underline underline-offset-2">LATAM private banking recruiter Geneva</Link></li>\n          <li><Link href="/en/mea-private-banking-recruiter-geneva" className="underline underline-offset-2">MEA private banking recruiter Geneva</Link></li>\n          <li><Link href="/en/nri-private-banking-recruiter-switzerland" className="underline underline-offset-2">NRI private banking recruiter Switzerland</Link></li>\n          <li><Link href="/en/israeli-market-private-banking-switzerland" className="underline underline-offset-2">Israeli market private banking Switzerland</Link></li>\n          <li><Link href="/en/hiring-managers" className="underline underline-offset-2">For hiring managers: brief a mandate</Link></li>\n          <li><Link href="/en/markets" className="underline underline-offset-2">All market hubs</Link></li>\n          <li><Link href="/en/private-banking-recruitment-agency" className="underline underline-offset-2">Private banking recruitment agency</Link></li>',"company Related section")
SWISS = "app/en/private-banking-recruiter-switzerland/page.tsx"
SWISS_FAQ = "\nconst faqJsonLd = {\n  '@context': 'https://schema.org',\n  '@type': 'FAQPage',\n  mainEntity: [\n    { '@type': 'Question', name: 'What does a private banking recruiter in Switzerland do?', acceptedAnswer: { '@type': 'Answer', text: 'A private banking recruiter in Switzerland identifies and places senior front-office bankers, primarily Senior Relationship Managers, Team Heads and Market Leaders, across Swiss private banks, EAMs and family offices in Geneva and Zurich. Every candidate is assessed for AUM portability, revenue quality and compliance history before any introduction is made.' } },\n    { '@type': 'Question', name: 'Do I need to be actively looking to speak with a private banking recruiter in Switzerland?', acceptedAnswer: { '@type': 'Answer', text: 'No. Most senior private bankers who contact Executive Partners are not actively looking. They want to understand their portability, benchmark their compensation, and assess which platforms would be the best strategic fit. All conversations are fully confidential.' } },\n    { '@type': 'Question', name: 'How long does a private banking placement take in Switzerland?', acceptedAnswer: { '@type': 'Answer', text: 'Senior private banking placements in Switzerland typically take eight to eighteen weeks from first conversation to signed offer, depending on mandate complexity, the number of interview stages, and notice period or non-compete agreements.' } },\n    { '@type': 'Question', name: 'Do you charge candidates for private banking recruitment in Switzerland?', acceptedAnswer: { '@type': 'Answer', text: 'No. Executive Partners never charges candidates at any stage. Our fees are paid exclusively by the hiring institution. Your profile is never shared without your explicit consent.' } },\n  ],\n}\n\n"
patch(SWISS,'export const metadata: Metadata = {',SWISS_FAQ + 'export const metadata: Metadata = {',"swiss faqJsonLd const")
patch(SWISS,'      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />','      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />\n      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />',"swiss FAQ script tag")
SWISS_FAQ_SEC = '\n        <h2 className="text-2xl font-semibold mt-12">Frequently Asked Questions</h2>\n        <div className="space-y-5 mt-4">\n          {[\n            { q: "What does a private banking recruiter in Switzerland do?", a: "A private banking recruiter in Switzerland identifies and places senior front-office bankers, primarily Senior Relationship Managers, Team Heads and Market Leaders, across Swiss private banks, EAMs and family offices in Geneva and Zurich. Every candidate is assessed for AUM portability, revenue quality and compliance history before any introduction is made." },\n            { q: "Do I need to be actively looking to speak with a recruiter?", a: "No. Most senior private bankers who contact Executive Partners are not actively looking. They want to understand their portability, benchmark their compensation, and assess which platforms would be the best strategic fit. All conversations are fully confidential." },\n            { q: "How long does a private banking placement take in Switzerland?", a: "Senior placements in Switzerland typically take eight to eighteen weeks from first conversation to signed offer, depending on mandate complexity, interview stages, and notice period or non-compete agreements." },\n            { q: "Do you charge candidates for your services?", a: "No. Executive Partners never charges candidates at any stage. Our fees are paid exclusively by the hiring institution. Your profile is never shared without your explicit consent." },\n          ].map(({q, a}) => (\n            <div key={q} className="border-t border-white/10 pt-5 pb-2">\n              <h3 className="text-white font-medium mb-2">{q}</h3>\n              <p className="text-white/60 text-sm leading-relaxed">{a}</p>\n            </div>\n          ))}\n        </div>\n\n'
patch(SWISS,'        <h2 className="text-2xl font-semibold mt-12">Apply Confidentially</h2>',SWISS_FAQ_SEC + '        <h2 className="text-2xl font-semibold mt-12">Apply Confidentially</h2>',"swiss visible FAQ")
SWISS_REL = '\n        <div className="border-t border-white/10 mt-10 pt-8">\n          <p className="text-xs uppercase tracking-widest text-white/30 mb-4">Related</p>\n          <ul className="space-y-2 text-sm text-white/50">\n            <li><a href="/en/markets/geneva" className="hover:text-white transition">Geneva private banking market hub</a></li>\n            <li><a href="/en/markets/zurich" className="hover:text-white transition">Zurich private banking market hub</a></li>\n            <li><a href="/en/latam-private-banking-recruiter-geneva" className="hover:text-white transition">LATAM private banking recruiter Geneva</a></li>\n            <li><a href="/en/mea-private-banking-recruiter-geneva" className="hover:text-white transition">MEA private banking recruiter Geneva</a></li>\n            <li><a href="/en/nri-private-banking-recruiter-switzerland" className="hover:text-white transition">NRI private banking recruiter Switzerland</a></li>\n            <li><a href="/en/israeli-market-private-banking-switzerland" className="hover:text-white transition">Israeli market private banking Switzerland</a></li>\n            <li><a href="/en/portability" className="hover:text-white transition">AUM Portability Score</a></li>\n            <li><a href="/en/bp-simulator" className="hover:text-white transition">Business Plan Simulator</a></li>\n          </ul>\n        </div>\n'
patch(SWISS,'      </div>\n      </main>',SWISS_REL + '      </div>\n      </main>',"swiss Related section")
print("\n✅ Part 1 complete.")
