export const crownChangesHandsBody = [
  "For thirty years, Geneva\u2019s claim to the top of the offshore wealth table was treated as a law of nature. Not a competitive position. Not something that required defending. A fact, like the Alps or the franc. The 2026 Global Wealth Report from Boston Consulting Group ended that assumption in a single data point.",
  "",
  "Hong Kong now books $2.95 trillion in cross-border private wealth. Switzerland books $2.94 trillion. The margin is $10 billion on a base of nearly $3 trillion, which is to say the margin is almost nothing. But the direction is everything. Boston Consulting Group, which has been tracking this convergence since at least 2022, is unambiguous: this reversal is unlikely to be undone. The hubs in Asia are growing faster than the European safe haven. The structural forces driving that divergence are not temporary.",
  "",
  "The reaction in Geneva has been some version of surprise. It should not have been.",
  "",
  "In 2022, the same institution published a forecast placing Hong Kong ahead of Switzerland before the end of that decade. The Swiss market noted it, debated it in conference panels, added it to the risk section of various strategy presentations, and largely continued as before. That is not a criticism unique to Switzerland. It is what incumbents do. The position felt safe enough that the urgency to act never quite materialised. The $10 billion gap is the cost of that calculation.",
  "",
  "## Where wealth actually gets created",
  "",
  "The mechanics of what happened are not complicated. Hong Kong\u2019s rise is a direct consequence of where wealth is being generated. China has been producing high-net-worth and ultra-high-net-worth individuals at a rate that no European economy can match. In 2021, the number of Chinese dollar millionaires surpassed the number of German ones. By 2025, Chinese billionaire creation was running at a pace that made Switzerland\u2019s own domestic wealth generation look almost static by comparison.",
  "",
  "A booking centre proximate to that wealth creation will attract assets. Hong Kong\u2019s geographic and cultural position as the gateway between mainland Chinese capital and international markets gives it a structural advantage that Geneva cannot replicate by improving its product offering or tightening its legal framework. The assets are created next door. The relationships are local. The language is Cantonese and Mandarin. The trust is generational and proximity-based.",
  "",
  "Boston Consulting Group\u2019s report projects that global financial wealth will grow at roughly 7 percent annually through 2030, assuming that geopolitical tensions and the energy shock ease in the second half of this year. The growth will not be evenly distributed. The fastest expansion will be in Asia, concentrated around the same wealth creation dynamic that has already pushed Hong Kong to the top of the rankings. Switzerland will grow too, but it will grow at a rate that reflects the slower accumulation of wealth in Western Europe and the continued regulatory friction that makes Swiss booking genuinely difficult for a category of clients who might otherwise choose Geneva.",
  "",
  "## The compliance posture and what it costs",
  "",
  "There is an uncomfortable conversation embedded in this data that the Swiss market has generally preferred to avoid. The compliance tightening of the past decade, accelerated dramatically by the events of 2022, has been necessary. The reputational damage from earlier eras, the pressure from FINMA, the cascading effects of the Credit Suisse collapse, and the political imperative to demonstrate that Swiss banking can clean itself up without external imposition, all of these made a stricter, more risk-averse posture not just defensible but essential.",
  "",
  "The cost is real, however. A significant proportion of the clients who might have historically booked in Geneva now find the process either too uncertain, too long, or simply too adversarial to be worth the effort. The enhanced due diligence requirements for certain nationalities, the source-of-wealth documentation burden, the restrictions on specific asset categories and geographies, these are not arbitrary inconveniences. They are the product of hard lessons learned at considerable expense. But they are also, as a practical matter, a filter that directs mobile wealth toward jurisdictions with a more accommodating posture.",
  "",
  "Hong Kong has not faced the same regulatory reckoning as Switzerland. Its compliance environment has its own complications, including a legal framework that is increasingly shaped by mainland political priorities in ways that create a different category of risk for internationally mobile clients. But for a specific and very large segment of Asian wealth, Hong Kong\u2019s compliance burden is simply less than Geneva\u2019s. The assets follow the path of least resistance, as they always have.",
  "",
  "Boston Consulting Group\u2019s note that Hong Kong\u2019s concentration on mainland China ties its trajectory tightly to economic and regulatory developments there is the other side of this ledger. A jurisdiction that derives its competitive advantage primarily from proximity to one country\u2019s wealth creation is exposed to that country\u2019s political and economic trajectory in a way that a genuinely neutral booking centre is not. Switzerland has lost the rankings race for now. It has not lost the argument about long-term stability and political neutrality, which remains the most durable value proposition in private banking for clients who need it most.",
  "",
  "## The talent question nobody is asking",
  "",
  "The conversation I have not seen in the coverage of this week\u2019s report is the one about people. Rankings and AUM figures describe outcomes. They do not explain the mechanism by which outcomes change. The mechanism is talent, and the talent question in Swiss private banking right now is more urgent than the market seems to appreciate.",
  "",
  "The banks that will win the next decade of cross-border wealth management are not the ones with the deepest balance sheet or the most comprehensive product platform. They are the ones with the right bankers in the right seats. Specifically, they are the banks that have invested in building teams with genuine Asian market capability sitting in Geneva and Zurich, not just in their Singapore or Hong Kong offices.",
  "",
  "Mandarin-speaking relationship managers who can service clients with Chinese wealth exposure from a Swiss booking platform are genuinely rare. The combination of private banking technical competence, language capability at a professional financial level, cultural intelligence, and Swiss regulatory literacy is not something you can hire easily or develop quickly. The banks that have those bankers are in a structurally stronger position than any product or platform advantage can create. The banks that have been treating Asian coverage as a regional matter handled from their Asian offices are building a dependency that leaves them exposed.",
  "",
  "This is not a theoretical observation. In the mandates I work on regularly, the difficulty of finding a senior relationship manager with credible Asian market coverage in Geneva is among the most consistent constraints I encounter. The candidate pool is thin. The competition for the few strong profiles that exist is intense. The compensation required to move them is high. And the lead time to build a team from scratch is measured in years, not quarters.",
  "",
  "The same logic applies, to varying degrees, to other growth markets. The bankers who will generate the next wave of AUM growth in Swiss private banking are disproportionately those who can access the sources of new wealth creation in Asia, in the Gulf, in Latin America, and in the diaspora communities of internationally mobile UHNW families. Building that coverage capability is a talent strategy, not a product strategy.",
  "",
  "## What Switzerland should do with a $10 billion gap",
  "",
  "The right response to this week\u2019s data is not panic and it is not defensive dismissal. It is a serious conversation about what the Swiss offshore model is actually for, who it serves best, and where its genuine competitive advantage lies in a world where proximity to Asian wealth creation is no longer available as a differentiating factor.",
  "",
  "Switzerland\u2019s case rests on rule of law, political neutrality, institutional stability, multi-generational banking relationships, and a regulatory framework that, for all its friction, provides genuine protection for clients who need predictability over a long time horizon. These are not trivial attributes. They are precisely the attributes that matter most to clients with genuine long-term wealth preservation needs, as distinct from clients who are primarily seeking to capitalise on near-term growth opportunities.",
  "",
  "The $10 billion margin between Hong Kong and Switzerland is not the story. The story is the structural divergence in wealth creation geography that produced it, and the question of whether Swiss private banking has built the human capability to access the next generation of that wealth. In some institutions, the answer is a cautious yes. In most, the honest answer is that the work is not yet done.",
  "",
  "That conversation needs to start now. The ranking has already changed. The talent pipeline takes years to build.",
  "",
  "---",
  "",
  "[1] Boston Consulting Group, Global Wealth Report 2026, published 27 May 2026. Cross-border AUM figures as of end-2025.",
  "[2] BCG Global Wealth Report 2022: forecast of Hong Kong displacing Switzerland as largest offshore booking centre.",
  "[3] Global financial wealth grew 10.7% in 2025, reaching $333 trillion. Equities contributed 13.2% and gold 44% of asset appreciation, BCG 2026.",
].join("\n");
