// @ts-nocheck
// Shared mandate data

export const MANDATES = [
  { id: "head-pb-development-swiss-onshore", listedDate: "2026-06-29", tag: "Switzerland · Swiss Onshore", title: "Head of Private Banking Development", subtitle: "Swiss Onshore, Commercial Client Conversion", location: "Geneva", flag: "🇨🇭", aum: "No book required", aum_note: "Internal client base provided, conversion role, not a portable book mandate", comp_base: "CHF 200K – 280K", comp_note: "base · uncapped variable indexed to personal and team production · no cap", urgent: true,
    profile_lines: ["Corporate or commercial banking profile, not a private banker. The bank is deliberately looking outside private banking for this seat", "Senior leadership of dedicated private banking teams covering the Geneva market, with a direct reporting line to the Head of Private Banking on the division's management committee", "Proven people leadership and the credibility to convert an existing commercial client base into private banking relationships, without personally managing day to day financing or credit activity"],
    brief: `A well-established Geneva-based bank has a specific problem to solve. It has a substantial commercial client base with genuine private banking potential that has never been systematically converted. The infrastructure and the private banking teams are already in place. What is missing is the right leader to bridge the gap between the commercial network and the private banking division.

This is not a role for a relationship manager bringing a portable book, and it is not a role for a private banker either. The bank is deliberately looking outside private banking for this seat. The mandate holder leads dedicated private banking teams covering the Geneva market across both domestic and international client segments. These bankers already manage wealth relationships day to day, that stays their responsibility. What the mandate holder owns is the conversion strategy, structuring and driving a disciplined process that turns high-potential commercial relationships into private banking mandates, working hand in hand with the bank's commercial network.

The role reports directly to the Head of Private Banking, who sits on the division's management committee, giving this position genuine weight and direct visibility at the top of the organization. The bridge to the bank's financing and commercial teams runs through a structured cross-selling process already in place, so this is a leadership and conversion mandate, not a day to day credit or financing role.

The right profile comes from a corporate or commercial banking background. They know how to speak the language of entrepreneurs and business owners, they understand what makes a commercial relationship ready for private banking, and they have led teams before with real accountability for results. This is a leadership role with a genuine transformation mandate, build the bridge, prove the model, scale it.

The bank is well established in the Geneva market and is prepared to give this person the autonomy and the mandate to build something meaningful. The client base exists. The private banking teams are in place. The opportunity is to connect the two.`,
    process: "Confidential call with Executive Partners · Assessment half-day · Senior panel introduction",
    screening: [
      { q: "How would you describe your banking background?", options: [{ label: "Corporate or commercial banking, entrepreneurs and business owners as core clients", pass: true }, { label: "Universal or retail banking background with branch network exposure", pass: true }, { label: "Pure private banking, I have always managed private client books", pass: false }, { label: "Investment banking or asset management", pass: false }] },
      { q: "Have you previously managed and led a team of relationship managers with KPI accountability?", options: [{ label: "No team management experience", pass: false }, { label: "Informal team lead — no direct reports", pass: "warn" }, { label: "Yes — managed a small team (2 to 4 RMs)", pass: true }, { label: "Yes — managed a team of 5 or more RMs with formal KPI targets", pass: true }] },
      { q: "What is your experience structuring or driving a cross-selling process between commercial and private banking divisions?", options: [{ label: "No experience with cross-selling initiatives", pass: false }, { label: "Some informal experience referring clients", pass: "warn" }, { label: "Yes, I have driven structured conversion initiatives", pass: true }, { label: "Yes, this was a core part of my mandate", pass: true }] },
      { q: "How familiar are you with working alongside a commercial bank branch network?", options: [{ label: "No experience — pure private banking environment", pass: false }, { label: "Some exposure but limited", pass: "warn" }, { label: "I have worked in or alongside a universal bank branch network", pass: true }, { label: "This was the core of my career — I know how branch networks operate", pass: true }] },
      { q: "What is your French language level?", options: [{ label: "Not fluent", pass: false }, { label: "Professional level", pass: true }, { label: "Native speaker", pass: true }] },
      { q: "Are you currently based in Geneva or the Romandie region, or open to relocating there?", options: [{ label: "Yes, already based there", pass: true }, { label: "Open to relocating", pass: true }, { label: "Not open to relocation", pass: false }] },
    ],
  },
  { id: "rm-brazil-ch", listedDate: "2026-06-15", tag: "LATAM · Brazil", title: "Senior Relationship Manager", subtitle: "Brazilian Market", location: "Zurich or Geneva", flag: "🇧🇷", aum: "CHF 250M+", aum_note: "3-year average portable book", comp_base: "CHF 180K – 280K", comp_note: "base · bonus · NPC buyout available", urgent: false,
    profile_lines: ["Personal ownership of Brazilian HNW and UHNW family relationships — not team or institutionally supported", "Minimum CHF 250M portable book measured over 3-year average", "5+ years managing Brazilian clients within a Swiss or international private bank"],
    brief: `A well-capitalised Swiss private bank with an established Latin American desk is looking to add a dedicated senior banker for the Brazilian market. This is not a build-from-scratch mandate — the infrastructure exists. What they need is a relationship manager who personally owns Brazilian HNW and UHNW client relationships and can demonstrate genuine portability.\n\nThe candidate has spent the majority of their private banking career managing Brazilian families and entrepreneurs, understands the specificities of Brazilian offshore wealth, knows the compliance and reporting framework, and holds relationships that are genuinely portable — meaning clients who would follow them, not clients managed within a shared team context.\n\nThe bank fully understands that LATAM portability takes time and is prepared to offer a structured NPC contribution and a realistic transition window. Location is Zurich or Geneva — both genuinely open.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "How many years have you personally managed Brazilian clients in a private banking context?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your current AUM under direct personal management (not team AUM)?", options: [{ label: "Under CHF 100M", pass: false }, { label: "CHF 100M – 200M", pass: "warn" }, { label: "CHF 200M – 350M", pass: true }, { label: "Over CHF 350M", pass: true }] },
      { q: "What proportion of your book do you believe is portable based on personal client relationships?", options: [{ label: "I'm not sure", pass: false }, { label: "Under 25%", pass: false }, { label: "25% – 50%", pass: "warn" }, { label: "Over 50%", pass: true }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
      { q: "Are you currently based in Switzerland or prepared to relocate to Zurich or Geneva?", options: [{ label: "Yes, already based there", pass: true }, { label: "Open to relocating", pass: true }, { label: "Not open to relocation", pass: false }] },
    ],
  },
  { id: "rm-argentina-ch", listedDate: "2026-06-15", tag: "LATAM · Argentina", title: "Senior Relationship Manager", subtitle: "Argentine Market", location: "Zurich or Geneva", flag: "🇦🇷", aum: "CHF 250M+", aum_note: "3-year average portable book", comp_base: "CHF 180K – 280K", comp_note: "base · bonus · NPC buyout available", urgent: false,
    profile_lines: ["Personal ownership of Argentine HNW and UHNW family or entrepreneur relationships", "Minimum CHF 250M portable book measured over 3-year average", "Deep understanding of Argentine offshore wealth and cross-border compliance"],
    brief: `A separate mandate from the Brazilian search — the hiring bank is the same, but the Argentine market operates on different dynamics and they are looking for a dedicated specialist, not a combined LATAM generalist.\n\nArgentine HNW and UHNW wealth has distinct characteristics: currency controls, capital flight history, the importance of trust built over years often spanning generations, and a client base that is acutely attuned to political risk. The right candidate understands these dynamics from experience, not from a briefing document.\n\nThe bank is realistic about portability timelines in this market and offers a structured transition package. Zurich or Geneva — both open.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "How many years have you personally managed Argentine clients in a private banking context?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your current AUM under direct personal management?", options: [{ label: "Under CHF 100M", pass: false }, { label: "CHF 100M – 200M", pass: "warn" }, { label: "CHF 200M – 350M", pass: true }, { label: "Over CHF 350M", pass: true }] },
      { q: "How familiar are you with Argentine offshore wealth structures and cross-border compliance?", options: [{ label: "No specific knowledge", pass: false }, { label: "General awareness only", pass: "warn" }, { label: "Working knowledge from experience", pass: true }, { label: "Deep expertise — managing it daily", pass: true }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
      { q: "Are you based in Switzerland or prepared to relocate to Zurich or Geneva?", options: [{ label: "Yes, already based there", pass: true }, { label: "Open to relocating", pass: true }, { label: "Not open to relocation", pass: false }] },
    ],
  },
  { id: "rm-frontalier-geneva", listedDate: "2026-05-18", tag: "Switzerland · Cross-Border", title: "Senior Relationship Manager", subtitle: "Franco-Genevois Cross-Border Market", location: "Geneva", flag: "🇫🇷🇨🇭", aum: "CHF 50M+", aum_note: "Portable cross-border book · French-domiciled HNW clients", comp_base: "CHF 140K – 220K", comp_note: "base · significant variable · NPC buyout available", urgent: true,
    profile_lines: ["Personal book of French-domiciled HNW and UHNW clients with genuine portability — not institutionally or team-held", "Hunter profile: proven track record of new client acquisition and net new money generation", "Swiss residency mandatory — valid Swiss work permit or right to work in Switzerland required · No exceptions"],
    brief: `A well-established Geneva-based institution with a genuine local franchise, strong credit capability and a recognised presence in the cross-border market is looking to add a dedicated senior banker for French-domiciled clientele.

This is not a build-from-scratch mandate. The platform exists, the infrastructure is in place, and the institution is known and respected in its market. What they need is a relationship manager who personally owns French-domiciled HNW and UHNW relationships — clients who bank with a banker, not with an institution — and who has the entrepreneurial drive to develop new ones.

The cross-border market between France and Geneva is a segment where trust, local network and long-term commitment make the difference. The right candidate knows this from experience. They have a track record of new client acquisition, a network of professional introducers (notaires, experts-comptables, family offices, entrepreneurs), and the discipline to manage a complex book within a rigorous FINMA and CDB20 framework.

Candidates with a current non-compete clause will receive structured transition support, including partial coverage of the garden leave period.`,
    process: "Confidential call with Executive Partners · Selective introduction · One senior meeting · No panels",
    screening: [
      { q: "What proportion of your current book consists of French-domiciled cross-border clients?", options: [{ label: "Under 20%", pass: false }, { label: "20% – 50%", pass: "warn" }, { label: "Over 50%", pass: true }, { label: "Almost exclusively cross-border / frontalier", pass: true }] },
      { q: "What is your AUM from French-domiciled clients under direct personal management (not team AUM)?", options: [{ label: "Under CHF 20M", pass: false }, { label: "CHF 20M – 50M", pass: "warn" }, { label: "CHF 50M – 120M", pass: true }, { label: "Over CHF 120M", pass: true }] },
      { q: "How would you describe your new business development track record over the last 3 years?", options: [{ label: "Primarily managing an existing inherited book", pass: false }, { label: "Some new client acquisition alongside existing book management", pass: "warn" }, { label: "Active hunter — consistent new client acquisition and NNM growth", pass: true }, { label: "Primarily new business — built most of my book from scratch", pass: true }] },
      { q: "What is your knowledge of Franco-Swiss cross-border wealth planning (fiscal conventions, IFI, succession)?", options: [{ label: "Limited — primarily investment advisory focus", pass: false }, { label: "Working knowledge from experience with cross-border clients", pass: true }, { label: "Deep — manage cross-border fiscal and succession situations regularly", pass: true }] },
      { q: "What is your French language level?", options: [{ label: "Not fluent", pass: false }, { label: "Professional level", pass: true }, { label: "Native speaker", pass: true }] },
      { q: "Are you currently resident in Switzerland (Geneva region)?", options: [{ label: "Yes — Swiss resident, Geneva or nearby", pass: true }, { label: "No — but I hold a Swiss work permit and am prepared to relocate immediately", pass: "warn" }, { label: "No — I reside in France or abroad", pass: false }] },
    ],
  },
  { id: "swiss-onshore-geneva", listedDate: "2026-05-01", tag: "Switzerland · Onshore", title: "Senior Relationship Manager", subtitle: "Swiss Onshore Market", location: "Geneva", flag: "🇨🇭", aum: "CHF 150M+", aum_note: "3-year average portable book", comp_base: "CHF 160K – 240K", comp_note: "base · performance bonus · retention structure", urgent: false,
    profile_lines: ["Swiss-resident HNW and UHNW book built through genuine advisory relationships — not institutionally held", "Minimum CHF 150M portable book measured over 3-year average", "Wealth planning and credit structuring depth valued · French an advantage"],
    brief: `Swiss onshore private banking at an institution with a genuine domestic franchise — strong balance sheet, real credit capability, and the wealth planning infrastructure that Swiss-domiciled HNW and UHNW clients expect.\n\nThe candidate manages Swiss-resident clients across HNW and UHNW, predominantly at UHNW level, with a book built over years of trusted advisory work. The distinction between clients who bank with an institution and clients who follow a banker is important here — this role requires the latter.\n\nThis is a Geneva-based role. No relocation dynamic.`,
    process: "Confidential call with Executive Partners · One meeting with hiring team",
    screening: [
      { q: "What proportion of your current book consists of Swiss-domiciled clients?", options: [{ label: "Under 30%", pass: false }, { label: "30% – 60%", pass: "warn" }, { label: "Over 60%", pass: true }, { label: "Exclusively Swiss onshore", pass: true }] },
      { q: "What is your AUM under direct personal management (not team AUM)?", options: [{ label: "Under CHF 80M", pass: false }, { label: "CHF 80M – 150M", pass: "warn" }, { label: "CHF 150M – 300M", pass: true }, { label: "Over CHF 300M", pass: true }] },
      { q: "How would you describe your Swiss wealth planning knowledge?", options: [{ label: "Limited — primarily investment advisory", pass: "warn" }, { label: "Working knowledge of Swiss fiscal structures", pass: true }, { label: "Deep — manage succession and estate planning regularly", pass: true }] },
      { q: "Are you currently based in Geneva or the Geneva region?", options: [{ label: "Yes", pass: true }, { label: "No but open to relocating to Geneva", pass: true }, { label: "No and not prepared to relocate", pass: false }] },
    ],
  },
  { id: "greece-cyprus-geneva", listedDate: "2026-06-15", tag: "Greece · Cyprus", title: "Senior Relationship Manager", subtitle: "Greek & Cypriot Market", location: "Geneva", flag: "🇬🇷🇨🇾", aum: "CHF 200M+", aum_note: "3-year average portable book", comp_base: "CHF 170K – 260K", comp_note: "base · competitive bonus · relocation support", urgent: false,
    profile_lines: ["Known in the Greek and Cypriot HNW and UHNW community — family or entrepreneur-level personal relationships", "Greek language fluency mandatory", "Minimum CHF 200M portable book measured over 3-year average"],
    brief: `A market where timing matters. Greek and Cypriot HNW and UHNW clients are currently reassessing long-standing bank relationships following institutional changes across the sector. A motivated banker with strong community relationships is unusually well-placed right now.\n\nThe hiring bank has an established Greek and Cypriot client base and wants to deepen it. They are not looking for a business developer without a book — they want a senior banker who is known in the community, speaks Greek fluently, and holds personal HNW and UHNW relationships built over years. A three-year average portable book of CHF 200M is the minimum.`,
    process: "Confidential introduction through Executive Partners · One senior meeting",
    screening: [
      { q: "What is your Greek language level?", options: [{ label: "No Greek", pass: false }, { label: "Basic / conversational", pass: false }, { label: "Fluent — use it professionally", pass: true }, { label: "Native speaker", pass: true }] },
      { q: "How many years have you personally managed Greek or Cypriot HNW and UHNW clients?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your AUM from Greek and Cypriot clients specifically?", options: [{ label: "Under CHF 80M", pass: false }, { label: "CHF 80M – 150M", pass: "warn" }, { label: "CHF 150M – 250M", pass: true }, { label: "Over CHF 250M", pass: true }] },
      { q: "Are you based in Geneva or prepared to relocate there?", options: [{ label: "Yes, already in Geneva", pass: true }, { label: "Open to relocating to Geneva", pass: true }, { label: "Not open to relocation", pass: false }] },
    ],
  },
  { id: "ia-cis-cee-geneva", listedDate: "2026-06-05", tag: "CIS · CEE · Russian-speaking", title: "Investment Advisor", subtitle: "CIS & CEE Market — Geneva", location: "Geneva", flag: "🇷🇺", aum: "No minimum", aum_note: "Bank provides existing client base", comp_base: "CHF 140K – 220K", comp_note: "base · advisory performance bonus", urgent: true,
    profile_lines: ["Perfectly fluent in French and English · Very good Russian mandatory", "CFA, CIIA or CWMA a strong asset · min. 5 years investment advisory in private banking", "Strong knowledge of equities, derivatives, fixed income, structured products · no book required"],
    brief: `The Investment Advisor is responsible for delivering tailored investment advice and portfolio strategies to high-net-worth and ultra-high-net-worth individuals from the CIS and CEE region. Working closely with Relationship Managers, the IA ensures clients receive comprehensive, risk-appropriate investment solutions aligned with their goals and profile.\n\nThis is a pure investment advisory mandate — not an RM role. The bank provides the client base. The candidate brings investment expertise: the ability to construct and optimise portfolios across asset classes, present strategies clearly, conduct regular portfolio reviews, and act as the trusted investment contact for existing clients in partnership with the RM team.\n\nThe role requires a university degree in Finance, Economics or equivalent. CFA, CIIA or CWMA is a strong asset. Minimum five years of experience in a similar investment advisory position within private banking. Very good knowledge of Russian is a strong differentiator for this mandate.`,
    process: "Direct introduction · Fast-track process for the right profile",
    screening: [
      { q: "What is your Russian language level?", options: [{ label: "None", pass: false }, { label: "Basic / beginner", pass: false }, { label: "Intermediate — can hold a conversation", pass: "warn" }, { label: "Fluent — use it with clients", pass: true }, { label: "Native speaker", pass: true }] },
      { q: "How many years have you worked as an Investment Advisor (not RM) in a private banking context?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 8 years", pass: true }, { label: "Over 8 years", pass: true }] },
      { q: "Which investment certifications do you hold?", options: [{ label: "None and not enrolled", pass: "warn" }, { label: "Enrolled / in progress", pass: "warn" }, { label: "CWMA", pass: true }, { label: "CFA or CIIA", pass: true }] },
      { q: "What is your hands-on experience with derivatives and structured products?", options: [{ label: "No experience", pass: false }, { label: "Theoretical knowledge only", pass: false }, { label: "Some exposure — assisted on transactions", pass: "warn" }, { label: "Regular execution experience", pass: true }] },
      { q: "Are you currently based in Geneva or prepared to work on-site there?", options: [{ label: "Yes, already in Geneva", pass: true }, { label: "Open to relocating to Geneva", pass: true }, { label: "No — remote only", pass: false }] },
    ],
  },
  { id: "ia-cis-cee-zurich", listedDate: "2026-06-05", tag: "CIS · CEE · Russian-speaking", title: "Investment Advisor", subtitle: "CIS & CEE Market — Zurich", location: "Zurich", flag: "🇷🇺", aum: "No minimum", aum_note: "Bank provides existing client base", comp_base: "CHF 140K – 220K", comp_note: "base · advisory performance bonus", urgent: true,
    profile_lines: ["Fluent Russian mandatory · German or French and English required", "CFA, CIIA or CWMA a strong asset · min. 5 years investment advisory in private banking", "Structured product execution experience required · no book needed"],
    brief: `A parallel mandate to the Geneva Investment Advisor search — a different institution, a separate CIS/CEE client base, based in Zurich. The investment advisory profile and client segment are comparable: Russian-speaking HNW and UHNW clients from the CIS and CEE region who require sophisticated, risk-appropriate investment advice.\n\nThe bank has an established book of CIS/CEE clients and is looking for an Investment Advisor with genuine product depth — someone who understands portfolio construction, can navigate derivatives and structured products with confidence, and builds trusted investment relationships over time.\n\nFor candidates open to both cities, Geneva and Zurich can be explored in parallel.`,
    process: "Direct introduction · Parallel process with Geneva mandate possible",
    screening: [
      { q: "What is your Russian language level?", options: [{ label: "None", pass: false }, { label: "Basic / beginner", pass: false }, { label: "Intermediate — can hold a conversation", pass: "warn" }, { label: "Fluent — use it with clients", pass: true }, { label: "Native speaker", pass: true }] },
      { q: "How many years have you worked as an Investment Advisor (not RM) in private banking?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 8 years", pass: true }, { label: "Over 8 years", pass: true }] },
      { q: "What certifications do you hold?", options: [{ label: "None and not enrolled", pass: "warn" }, { label: "Enrolled / in progress", pass: "warn" }, { label: "CWMA", pass: true }, { label: "CFA or CIIA", pass: true }] },
      { q: "Are you based in Zurich or the greater Zurich area, or open to relocating?", options: [{ label: "Yes, already in Zurich area", pass: true }, { label: "Open to relocating to Zurich", pass: true }, { label: "No — Geneva only or remote", pass: false }] },
    ],
  },
  { id: "rm-italy-ch", listedDate: "2026-05-05", tag: "Italy · Italian Market", title: "Senior Relationship Manager", subtitle: "Italian Market", location: "Zurich, Geneva or Lugano", flag: "🇮🇹", aum: "CHF 200M+", aum_note: "3-year average portable book", comp_base: "CHF 180K – 300K", comp_note: "base · performance bonus · NPC buyout available", urgent: false,
    profile_lines: ["Personal ownership of Italian HNW and UHNW client relationships managed from a Swiss booking centre", "Minimum CHF 200M portable book measured over 3-year average — Italian clients specifically", "Cross-border regulatory expertise (Italy / Switzerland) and Italian language mandatory"],
    brief: `A Swiss-based mandate covering the Italian market — Zurich, Geneva or Lugano, with the location determined by the candidate's preference and the bank's team structure. All three are genuinely open.\n\nThe hiring bank has a well-established Italian client franchise and wants to add a senior relationship manager who personally owns Italian HNW and UHNW relationships. This is not a greenfield mandate — the infrastructure, booking centre and product access are already in place. What they need is a banker with a real, portable Italian book who can deepen and develop existing relationships while selectively bringing their own.\n\nThe ideal candidate has spent the majority of their private banking career managing Italian clients from a Swiss platform, understands the cross-border regulatory framework on both sides, operates at the level of succession planning, real estate structuring and multi-generational family wealth rather than pure investment allocation, and holds relationships in their own name rather than through a team structure. A three-year average portable book of CHF 200M from Italian clients is the minimum threshold.\n\nLugano is particularly relevant for bankers with strong ties to the Northern Italian corridor. Geneva and Zurich suit candidates with a broader Italian UHNW offshore client base.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "What is your Italian language level?", options: [{ label: "None", pass: false }, { label: "Basic / intermediate", pass: false }, { label: "Fluent — professional use", pass: true }, { label: "Native speaker", pass: true }] },
      { q: "How many years have you personally managed Italian clients from a Swiss booking centre?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your total AUM from Italian clients under direct personal management (not team AUM)?", options: [{ label: "Under CHF 80M", pass: false }, { label: "CHF 80M – 150M", pass: "warn" }, { label: "CHF 150M – 300M", pass: true }, { label: "Over CHF 300M", pass: true }] },
      { q: "How would you describe your knowledge of Italian cross-border compliance and Swiss-Italian regulatory requirements?", options: [{ label: "Limited — primarily investment advisory", pass: "warn" }, { label: "Working knowledge from experience", pass: true }, { label: "Deep expertise — managing it daily", pass: true }] },
      { q: "Are you currently based in Switzerland (Zurich, Geneva or Lugano) or prepared to relocate there?", options: [{ label: "Yes, already based in Switzerland", pass: true }, { label: "Open to relocating to Switzerland", pass: true }, { label: "Not open to Switzerland", pass: false }] },
    ],
  },
  { id: "rm-italy-milan", listedDate: "2026-05-05", tag: "Italy · Italian Market", title: "Senior Relationship Manager", subtitle: "Italian Market", location: "Milan", flag: "🇮🇹", aum: "CHF 180M+", aum_note: "3-year average portable book", comp_base: "EUR 150K – 250K", comp_note: "base · performance bonus · business plan support", urgent: false,
    profile_lines: ["Career focused on Italian HNW and UHNW entrepreneur and family clients · Italian mandatory", "Cross-border regulatory knowledge (Italy / Switzerland) valued", "Managing succession, real estate structuring and multi-generational wealth conversations"],
    brief: `A Milan-based role at a bank with a genuine and growing Italian franchise. This is not a greenfield mandate — the bank has an existing Italian client base and wants to strengthen it at the senior level.\n\nThe right profile has spent the majority of a private banking career managing Italian HNW and UHNW clients and entrepreneurs, understands the regulatory environment on both sides of the border, and operates at the level of wealth structuring, succession and multi-generational planning.\n\nA three-year average portable book of CHF 180M is the minimum. The hiring institution is in the process of upgrading its Italian presence from a representative office to a fully licensed advisory operation — a significant platform commitment that opens meaningful long-term opportunities for a senior banker building a serious Italian franchise. Italian fluency is mandatory. The role is Milan-based; remote coverage is not an option.`,
    process: "Confidential introduction · One meeting with Geneva and Milan leadership",
    screening: [
      { q: "What is your Italian language level?", options: [{ label: "None", pass: false }, { label: "Basic / intermediate", pass: false }, { label: "Fluent — professional use", pass: true }, { label: "Native speaker", pass: true }] },
      { q: "What proportion of your current book consists of Italian HNW and UHNW clients?", options: [{ label: "Under 30%", pass: false }, { label: "30% – 60%", pass: "warn" }, { label: "Over 60%", pass: true }, { label: "Exclusively Italian clients", pass: true }] },
      { q: "What is your total AUM from Italian clients under direct personal management?", options: [{ label: "Under CHF 50M", pass: false }, { label: "CHF 50M – 120M", pass: "warn" }, { label: "CHF 120M – 250M", pass: true }, { label: "Over CHF 250M", pass: true }] },
      { q: "Are you based in Milan or prepared to be based there full-time?", options: [{ label: "Yes, already in Milan", pass: true }, { label: "Open to relocating to Milan", pass: true }, { label: "No — not open to Milan", pass: false }] },
    ],
  },
  { id: "rm-hong-kong", listedDate: "2026-06-15", tag: "Asia Pacific · Hong Kong", title: "Senior Relationship Manager", subtitle: "Hong Kong", location: "Hong Kong", flag: "🇭🇰", aum: "USD/CHF 250M+", aum_note: "3-year average portable book", comp_base: "HKD 1.8M – 3M", comp_note: "base equivalent · bonus · relocation contribution", urgent: false,
    profile_lines: ["Personal HNW and UHNW relationships — Greater China, Southeast Asia or international clients booked in HK", "Minimum USD/CHF 250M portable book over 3-year average", "Mandarin or Cantonese an advantage · relocation package available"],
    brief: `A senior RM mandate at a private bank with a well-established Hong Kong presence and a client base spanning Greater China, Southeast Asia and international markets. The bank is hiring selectively at the senior level.\n\nThe candidate manages HNW and UHNW relationships personally and can demonstrate portability based on the depth and tenure of those relationships, not institutional loyalty. The bank places a premium on relationship quality — a banker with fifteen truly owned relationships is more interesting than one with fifty that belong to the institution.\n\nHong Kong residency or a firm willingness to relocate is required. The bank offers a competitive relocation package for the right candidate.`,
    process: "Confidential call with Executive Partners · Single introduction to hiring team",
    screening: [
      { q: "What is your total AUM under direct personal management?", options: [{ label: "Under USD 100M", pass: false }, { label: "USD 100M – 200M", pass: "warn" }, { label: "USD 200M – 350M", pass: true }, { label: "Over USD 350M", pass: true }] },
      { q: "What is the average tenure of your top 10 client relationships?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "Over 10 years", pass: true }] },
      { q: "Do you hold or are you eligible for an SFC licence in Hong Kong?", options: [{ label: "Yes — active SFC licence", pass: true }, { label: "Previously held — can reactivate", pass: true }, { label: "Not yet but prepared to obtain one", pass: "warn" }, { label: "No and not interested", pass: false }] },
      { q: "Are you currently based in Hong Kong or prepared to relocate there?", options: [{ label: "Yes, based in Hong Kong", pass: true }, { label: "Open to relocating", pass: true }, { label: "No — not open to Hong Kong", pass: false }] },
    ],
  },
  { id: "rm-singapore", listedDate: "2026-06-15", tag: "Asia Pacific · Singapore", title: "Senior Relationship Manager", subtitle: "Singapore", location: "Singapore", flag: "🇸🇬", aum: "CHF 250M+", aum_note: "3-year average portable book", comp_base: "SGD 280K – 450K", comp_note: "base · performance bonus · senior platform", urgent: false,
    profile_lines: ["Deep personal HNW and UHNW relationships — Southeast Asian, South Asian or international clients in Singapore", "Minimum CHF 250M portable book over 3-year average", "Family office, succession and multi-booking-centre experience valued"],
    brief: `Singapore-based private banking at an institution with a strong HNW and UHNW franchise. The bank is building at the senior level with deliberate selectivity — they are not filling a vacancy, they are adding a banker who genuinely strengthens the team.\n\nThe profile is a senior RM with deep, personally owned HNW and UHNW relationships and a portable book of CHF 250M or above on a three-year average. The bank values relationship depth over market breadth — a banker with fifteen deep relationships they truly own is more interesting than one with fifty superficial ones.\n\nMAS licence or eligibility is required. Singapore residency or willingness to relocate is expected.`,
    process: "Confidential call with Executive Partners · One meeting with senior leadership",
    screening: [
      { q: "What is your total AUM under direct personal management?", options: [{ label: "Under CHF 100M", pass: false }, { label: "CHF 100M – 200M", pass: "warn" }, { label: "CHF 200M – 350M", pass: true }, { label: "Over CHF 350M", pass: true }] },
      { q: "How many of your top clients have followed you from a previous institution?", options: [{ label: "None — all clients stayed at my last bank", pass: false }, { label: "A few — 1 to 3 clients", pass: "warn" }, { label: "Several — 4 or more clients", pass: true }, { label: "Most of my book has followed me before", pass: true }] },
      { q: "Do you hold or are you eligible for a MAS Capital Markets Services licence?", options: [{ label: "Yes — active MAS licence", pass: true }, { label: "Previously held — can reactivate", pass: true }, { label: "Not yet but prepared to obtain one", pass: "warn" }, { label: "No and not interested", pass: false }] },
      { q: "Are you currently based in Singapore or prepared to relocate there?", options: [{ label: "Yes, based in Singapore", pass: true }, { label: "Open to relocating", pass: true }, { label: "No — not open to Singapore", pass: false }] },
    ],
  },
  { id: "rm-uk-geneva", listedDate: "2026-05-08", tag: "United Kingdom · UK Market", title: "Senior Relationship Manager", subtitle: "UK Market", location: "Geneva", flag: "🇬🇧", aum: "CHF 150M+", aum_note: "3-year average portable book — non-dom transition acknowledged", comp_base: "CHF 180K – 280K", comp_note: "base · bonus · NPC buyout available", urgent: false,
    profile_lines: ["Personal ownership of UK HNW and UHNW client relationships managed from Geneva", "Minimum CHF 250M portable book measured over 3-year average — UK clients specifically", "Understanding of UK resident and non-domiciled client structures · cross-border compliance knowledge"],
    brief: `A Geneva-based mandate covering the UK market. The hiring bank has an established British and UK-resident client base and is looking to strengthen its senior coverage with a relationship manager who personally owns HNW and UHNW relationships with UK families, entrepreneurs, non-domiciled residents and internationally mobile professionals.

The UK private wealth market from a Swiss booking centre has particular characteristics: non-dom structures, remittance basis planning, UK-resident clients with international assets, and families with multi-jurisdictional footprints that require careful cross-border coordination. The right candidate understands these dynamics in practice, not just in principle.

The ideal profile has spent a meaningful part of their private banking career managing UK clients from a Swiss or international platform, holds relationships in their own name, and can demonstrate genuine portability based on personal client trust rather than institutional proximity. A three-year average portable book of CHF 150M from UK clients is the minimum threshold. The bank is aware of the non-dom regime changes effective April 2025 and takes a considered view on AUM trajectory — relationship quality and portability depth are weighted alongside current book size.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "How many years have you personally managed UK clients in a private banking context?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your current AUM under direct personal management from UK clients (not team AUM)?", options: [{ label: "Under CHF 100M", pass: false }, { label: "CHF 100M – 150M", pass: "warn" }, { label: "CHF 150M – 300M", pass: true }, { label: "Over CHF 300M", pass: true }] },
      { q: "How familiar are you with UK non-dom structures, remittance basis planning and UK cross-border compliance?", options: [{ label: "No specific knowledge", pass: false }, { label: "General awareness only", pass: "warn" }, { label: "Working knowledge from experience", pass: true }, { label: "Deep expertise — managing it daily", pass: true }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
      { q: "Are you currently based in Geneva or prepared to relocate there?", options: [{ label: "Yes, already in Geneva", pass: true }, { label: "Open to relocating to Geneva", pass: true }, { label: "Not open to relocation", pass: false }] },
    ],
  },
  { id: "rm-south-africa-geneva", listedDate: "2026-05-08", tag: "Africa · South Africa", title: "Senior Relationship Manager", subtitle: "South African Market", location: "Geneva", flag: "🇿🇦", aum: "CHF 200M+", aum_note: "3-year average portable book", comp_base: "CHF 170K – 270K", comp_note: "base · bonus · NPC buyout available", urgent: false,
    profile_lines: ["Personal ownership of South African HNW and UHNW client relationships — not institutionally held", "Minimum CHF 250M portable book measured over 3-year average", "Deep knowledge of South African offshore wealth, exchange control regulations and cross-border compliance"],
    brief: `A Geneva-based mandate for a senior private banker with a genuinely owned South African client base. The hiring bank has an established African desk and is looking to strengthen its South African coverage with a relationship manager who holds personal UHNW and HNW relationships — families, entrepreneurs and business owners who have accumulated wealth offshore and require sophisticated wealth management solutions from a serious Swiss platform.\n\nThe right candidate has spent the majority of their private banking career managing South African clients, understands the nuances of South African exchange control regulations and the SARB framework, knows how to structure compliant cross-border wealth arrangements, and holds relationships that are genuinely portable — built on personal trust rather than institutional loyalty.\n\nSouth Africa is a market where relationship depth matters considerably more than institutional brand. The bank offers a strong platform, competitive NPC contribution and a realistic transition window for the right profile.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "How many years have you personally managed South African clients in a private banking context?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your current AUM under direct personal management from South African clients (not team AUM)?", options: [{ label: "Under CHF 100M", pass: false }, { label: "CHF 100M – 150M", pass: "warn" }, { label: "CHF 150M – 250M", pass: true }, { label: "Over CHF 250M", pass: true }] },
      { q: "How familiar are you with South African exchange control regulations and SARB compliance requirements?", options: [{ label: "No specific knowledge", pass: false }, { label: "General awareness only", pass: "warn" }, { label: "Working knowledge from experience", pass: true }, { label: "Deep expertise — managing it daily", pass: true }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
      { q: "Are you currently based in Geneva or prepared to relocate there?", options: [{ label: "Yes, already in Geneva", pass: true }, { label: "Open to relocating to Geneva", pass: true }, { label: "Not open to relocation", pass: false }] },
    ],
  },
  { id: "rm-south-africa-london", listedDate: "2026-05-08", tag: "Africa · South Africa", title: "Senior Relationship Manager", subtitle: "South African Market", location: "London", flag: "🇿🇦", aum: "CHF 200M+", aum_note: "3-year average portable book", comp_base: "GBP 150K – 250K", comp_note: "base · bonus · NPC buyout available", urgent: false,
    profile_lines: ["Personal ownership of South African HNW and UHNW client relationships managed from London", "Minimum CHF 250M portable book measured over 3-year average", "Understanding of South African offshore wealth, exchange control and cross-border compliance from a UK booking centre"],
    brief: `A London-based mandate covering the South African market — a separate search from the Geneva role, different institution, different booking centre, different team structure. Both can be explored in parallel for candidates open to either city.\n\nLondon is a natural hub for South African private wealth — proximity to the diaspora community, strong legal and structuring infrastructure, and a client base that is comfortable with a UK booking centre. The hiring bank has an established South African client base in London and is looking for a senior relationship manager who personally owns HNW and UHNW relationships with South African families, entrepreneurs and business owners.\n\nThe right candidate understands South African offshore wealth dynamics — exchange control, SARB compliance, the motivations behind offshore structuring — and holds relationships that have been built over years of trusted personal advisory work rather than institutional proximity. A three-year average portable book of CHF 250M is the minimum threshold.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "How many years have you personally managed South African clients in a private banking context?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your current AUM under direct personal management from South African clients (not team AUM)?", options: [{ label: "Under CHF 100M", pass: false }, { label: "CHF 100M – 150M", pass: "warn" }, { label: "CHF 150M – 250M", pass: true }, { label: "Over CHF 250M", pass: true }] },
      { q: "How familiar are you with South African exchange control regulations and SARB compliance requirements?", options: [{ label: "No specific knowledge", pass: false }, { label: "General awareness only", pass: "warn" }, { label: "Working knowledge from experience", pass: true }, { label: "Deep expertise — managing it daily", pass: true }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
      { q: "Are you currently based in London or prepared to relocate there?", options: [{ label: "Yes, already in London", pass: true }, { label: "Open to relocating to London", pass: true }, { label: "Not open to relocation", pass: false }] },
    ],
  },

  { id: "rm-latam-new-york", listedDate: "2026-06-15", tag: "LATAM · New York", title: "Senior Relationship Manager", subtitle: "LATAM Market — Argentine, Brazilian or Mexican Clients", location: "New York", flag: "🇺🇸", seniority: "Director / Executive Director", aum: "USD 300M+", aum_note: "3-year average portable book", comp_base: "USD 220K – 380K", comp_note: "base · performance bonus · NPC buyout available", urgent: false,
    profile_lines: ["Personal ownership of HNW and UHNW client relationships from one core LATAM market — Argentina, Brazil or Mexico — built over years of direct personal advisory work", "Minimum USD 300M portable book measured over 3-year average from LATAM clients specifically", "Deep familiarity with LATAM offshore wealth dynamics, cross-border compliance and US booking centre requirements", "Spanish and/or Portuguese fluency mandatory · US work authorisation required"],
    brief: `A major international bank with one of the deepest Latin American franchises in the world is looking to strengthen its New York private banking desk with a senior relationship manager who has built a genuinely portable book within one core LATAM market — Argentina, Brazil or Mexico. The bank is not looking for a generalist with superficial coverage across the region. They want a banker who is deeply embedded in one community, speaks the language fluently, and holds client relationships that have been built over years of trusted personal advisory work.\n\nThis is not a greenfield mandate. The bank has an established and well-resourced Latin American platform in New York, with significant infrastructure, product breadth, and an existing client base. What they need is a senior banker who brings a genuinely portable book and the kind of long-standing personal client relationships that do not belong to an institution — they belong to the banker.\n\nThe typical client profile spans ultra-high-net-worth families, business owners, and internationally mobile entrepreneurs from the Southern Cone and Mexico, many of whom have maintained US-booked wealth for decades. The bank understands LATAM portability dynamics and is prepared to offer a structured NPC contribution and a realistic transition window for the right candidate.\n\nNew York residency or the ability to be based there full-time is required. US work authorisation is a hard requirement. The role sits within a senior team and carries genuine autonomy — this is not a junior-supported position.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "Which single LATAM market makes up the core of your personal client book?", options: [{ label: "Argentina", pass: true }, { label: "Brazil", pass: true }, { label: "Mexico", pass: true }, { label: "Mixed — no single dominant market", pass: false }] },
      { q: "What is your total AUM under direct personal management from LATAM clients?", options: [{ label: "Under USD 100M", pass: false }, { label: "USD 100M – 200M", pass: "warn" }, { label: "USD 200M – 400M", pass: true }, { label: "Over USD 400M", pass: true }] },
      { q: "What proportion of your book do you believe is portable based on personal client relationships?", options: [{ label: "I am not sure", pass: false }, { label: "Under 25%", pass: false }, { label: "25% – 50%", pass: "warn" }, { label: "Over 50%", pass: true }] },
      { q: "What is your Spanish or Portuguese language level?", options: [{ label: "Neither", pass: false }, { label: "Basic only", pass: false }, { label: "Fluent in one", pass: true }, { label: "Fluent in both", pass: true }] },
      { q: "Do you currently have US work authorisation (citizen, green card, or valid visa)?", options: [{ label: "Yes — citizen or green card", pass: true }, { label: "Yes — valid work visa", pass: true }, { label: "No — would require sponsorship", pass: false }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
    ],
  },
  { id: "rm-saudi-riyadh-geneva", listedDate: "2026-06-12", tag: "MEA · Saudi Arabia", title: "Senior Relationship Manager", subtitle: "Saudi / GCC Market", location: "Riyadh or Geneva", flag: "🇸🇦", aum: "CHF 250M+", aum_note: "3-year average portable book, Saudi/GCC clients", comp_base: "Competitive base · bonus", comp_note: "structure aligned to location (Riyadh or Geneva)", urgent: true,
    profile_lines: ["Personal ownership of Saudi and wider GCC HNW/UHNW relationships — not team or institutionally supported", "Minimum CHF 250M portable book measured over 3-year average", "5+ years managing Saudi/GCC clients within a private bank or EAM, based in Riyadh, Geneva or a comparable Gulf/Swiss booking centre", "Arabic fluency a strong differentiator for Riyadh-based candidates"],
    brief: `An established international private banking platform is expanding its Saudi and wider GCC coverage and is looking to add a senior relationship manager who can be based either in Riyadh or in Geneva, depending on the candidate's profile and where their book is best served.\n\nThis is a confidential mandate for a platform with existing Saudi/GCC infrastructure, regulatory approvals and booking capability — not a greenfield build. The successful candidate will bring a personally owned book of Saudi and regional GCC clients, genuinely portable, and will be supported by an established platform spanning onshore Riyadh coverage and offshore Geneva booking.\n\nCandidates based in Riyadh should have strong Arabic-language client coverage experience and familiarity with onboarding under the Saudi regulatory framework (SAMA/CMA). Candidates based in Geneva should have a demonstrable track record of managing Saudi/GCC relationships from a Swiss platform with cross-border compliance discipline.\n\nLocation is genuinely open between Riyadh and Geneva and will be determined together with the successful candidate based on where their relationships and personal circumstances are best served.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "How many years have you personally managed Saudi or wider GCC HNW/UHNW clients?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your 3-year average portable book for Saudi/GCC clients?", options: [{ label: "Under CHF 150M", pass: false }, { label: "CHF 150M – 250M", pass: "warn" }, { label: "CHF 250M – 400M", pass: true }, { label: "Over CHF 400M", pass: true }] },
      { q: "Are you open to being based in Riyadh, Geneva, or either?", options: [{ label: "Riyadh only", pass: true }, { label: "Geneva only", pass: true }, { label: "Open to either", pass: true }, { label: "Neither — other location only", pass: false }] },
      { q: "Do you have Arabic-language client coverage experience?", options: [{ label: "Native or fluent Arabic", pass: true }, { label: "Working proficiency", pass: "warn" }, { label: "No Arabic", pass: "warn" }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
    ],
  },
  { id: "rm-mea-dubai", listedDate: "2026-06-13", tag: "MEA · Dubai (DIFC)", title: "Senior Relationship Manager", subtitle: "GCC, Levant, Africa & India Coverage", location: "Dubai (DIFC)", flag: "🇦🇪", aum: "USD 150M+", aum_note: "3-year average portable book, GCC/Levant/Africa/India clients", comp_base: "USD 200K – 400K", comp_note: "base · bonus · tax-free", urgent: false,
    profile_lines: ["Personal ownership of UHNW/HNW relationships across GCC, Levant, Africa or India — not team or institutionally supported", "Minimum USD 150M portable book measured over 3-year average", "5+ years private banking experience based in Dubai DIFC or a comparable Gulf booking centre", "Arabic and English required; French, Hindi or Urdu a strong differentiator depending on desk"],
    brief: `An established international private banking platform in the DIFC is expanding its regional coverage team and is looking to add a senior relationship manager with a personally owned book spanning GCC, Levant, African or Indian UHNW and HNW clients.\n\nThis is a confidential mandate for a platform with existing DFSA licensing, booking capability and a genuinely multilingual coverage team — not a greenfield build. The successful candidate will bring a portable book with proven revenue and a strong compliance culture, and will be supported by an established product shelf spanning advisory, Lombard lending, private markets and real estate financing.\n\nThe platform is calibrating carefully on booking options, credit appetite and product fit, so business plans built on realistic wallet share rather than optimistic projections are essential. Candidates who combine Arabic and English with French, Hindi or Urdu are particularly well positioned for the broader GCC, Levant, Africa and India corridor this desk covers.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "How many years have you personally managed GCC, Levant, African or Indian HNW/UHNW clients?", options: [{ label: "Under 2 years", pass: false }, { label: "2 – 4 years", pass: "warn" }, { label: "5 – 9 years", pass: true }, { label: "10 years or more", pass: true }] },
      { q: "What is your 3-year average portable book for these client segments?", options: [{ label: "Under USD 75M", pass: false }, { label: "USD 75M – 150M", pass: "warn" }, { label: "USD 150M – 300M", pass: true }, { label: "Over USD 300M", pass: true }] },
      { q: "Which languages do you speak fluently, in addition to English?", options: [{ label: "Arabic only", pass: true }, { label: "Arabic plus French, Hindi or Urdu", pass: true }, { label: "French, Hindi or Urdu without Arabic", pass: "warn" }, { label: "None of the above", pass: "warn" }] },
      { q: "Are you currently based in Dubai DIFC or open to relocating there?", options: [{ label: "Yes, already based there", pass: true }, { label: "Open to relocating", pass: true }, { label: "Not open to relocation", pass: false }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
    ],
  },
  { id: "rm-israeli-market-tel-aviv", listedDate: "2026-06-19", tag: "Israeli Market · Tel Aviv", title: "Senior Relationship Manager", subtitle: "Israeli Market — UHNW/HNW Coverage", location: "Tel Aviv", flag: "🇮🇱", aum: "Book provided", aum_note: "Existing client book assigned from day one — no portable AUM required", comp_base: "CHF 160K – 280K", comp_note: "base · bonus · calibrated to Director/Senior Director level", urgent: false,
    profile_lines: ["Active ISA investment advisory licence — strict requirement for this onshore position", "Minimum eight years of private banking experience with dedicated Israeli UHNW/HNW client coverage", "Hebrew fluency at a professional client-facing level — non-negotiable for this role"],
    brief: `A leading European private bank with a well-established onshore presence in Tel Aviv and a strong cross-border platform covering Swiss and European booking centres is seeking a Senior Relationship Manager to join and strengthen its Israeli-market coverage team.\n\nThis is an institutional appointment within a structured and well-resourced desk. The incoming banker will assume a defined client book from day one, covering Israeli UHNW and HNW clients. The mandate is to consolidate and deepen those relationships, drive incremental wallet share, and selectively identify new business opportunities within the Israeli market. This is a quality-focused, relationship-driven role rather than a pure hunter mandate.\n\nIsrael is one of the most concentrated pools of technology-generated private wealth outside the United States. Bankers who understand liquidity events, founder wealth structures, family succession and the specific dynamics of cross-border booking between Israel and European financial centres carry a significant advantage in this market.\n\nThe bank offers a structured platform, strong institutional backing, cross-border investment capabilities and a credible long-term commitment to the Israeli market. The institution's name is disclosed following a qualifying introductory conversation with Executive Partners.`,
    process: "Confidential call with Executive Partners · Single senior introduction · No panels",
    screening: [
      { q: "Do you currently hold an active ISA investment advisory licence?", options: [{ label: "Yes — active ISA advisory licence", pass: true }, { label: "Previously held, currently lapsed", pass: false }, { label: "No ISA licence", pass: false }] },
      { q: "How many years have you personally managed Israeli UHNW or HNW clients in a private banking context?", options: [{ label: "Under 3 years", pass: false }, { label: "3 – 7 years", pass: "warn" }, { label: "8 – 12 years", pass: true }, { label: "Over 12 years", pass: true }] },
      { q: "What is your level of Hebrew fluency for client-facing work?", options: [{ label: "Native or mother-tongue", pass: true }, { label: "Fluent — full professional proficiency", pass: true }, { label: "Conversational only", pass: false }, { label: "No Hebrew", pass: false }] },
      { q: "Do you have experience managing client relationships arising from Israeli tech liquidity events or founder wealth?", options: [{ label: "Yes — core part of my book", pass: true }, { label: "Some exposure", pass: "warn" }, { label: "No specific experience", pass: "warn" }] },
      { q: "Do you currently have a non-compete or non-solicit agreement?", options: [{ label: "No NCA / NDA", pass: true }, { label: "Yes — under 6 months", pass: true }, { label: "Yes — 6 to 12 months", pass: "warn" }, { label: "Yes — over 12 months", pass: false }] },
    ],
  },
];

export type MandateOption = { label: string; pass: boolean | "warn" };
export type MandateScreening = { q: string; options: MandateOption[] };
export type Mandate = {
  id: string; tag: string; title: string; subtitle: string;
  location: string; flag: string; aum: string; aum_note: string;
  comp_base: string; comp_note: string; urgent: boolean;
  profile_lines: string[]; brief: string; process: string;
  screening: MandateScreening[]; ubp_ref?: string;
};
