// lib/reports/fitAssessmentReport.ts
//
// Generates an EP-branded PDF for FitAssessmentV2 results.
// Matches the exact JSON shape returned by app/api/fit-assessment-v2/route.ts.
//
// IMPORTANT: pdf-lib's standard fonts (Helvetica) only support WinAnsi
// encoding (roughly Latin-1). Emoji (flags, etc.) and other extended
// Unicode characters will throw at draw time if not stripped first —
// sanitizeText() below handles this for every piece of dynamic text.
//
// Install once: npm install pdf-lib

import { PDFDocument, StandardFonts, rgb, PageSizes, PDFFont, PDFPage } from "pdf-lib";

const NAVY = rgb(0x1b / 255, 0x3a / 255, 0x6b / 255);
const GOLD = rgb(0xc9 / 255, 0xa1 / 255, 0x4a / 255);
const DARK_TEXT = rgb(0.15, 0.15, 0.15);
const GREY_TEXT = rgb(0.4, 0.4, 0.4);
const LIGHT_LINE = rgb(0.85, 0.85, 0.85);

const MARGIN = 50;
const PAGE_W = PageSizes.A4[0];
const PAGE_H = PageSizes.A4[1];
const CONTENT_W = PAGE_W - MARGIN * 2;

function sanitizeText(text: string | undefined | null): string {
  if (!text) return "";
  return text
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/[^\x00-\xFF]/g, "") // strips emoji flags + any other non-Latin1 char
    .replace(/\s+/g, " ")
    .trim();
}

export interface FitFormData {
  name?: string;
  email: string;
}

export interface TopMarket {
  city: string;
  flag?: string;
  fitLevel: string;
  rationale: string;
  hiringContext?: string;
  keyRequirement?: string;
}

export interface MatchedMandate {
  id: string;
  title: string;
  subtitle?: string;
  location: string;
  aum?: string;
  flag?: string;
}

export interface FitResult {
  headline: string;
  overallFit: string;
  positioning: string;
  commercialSummary: string;
  topMarkets: TopMarket[];
  strengths: string[];
  gaps: string[];
  legalNote?: string;
  timingNote?: string;
  epAssessment: string;
  urgency: string;
  matchedMandates?: MatchedMandate[];
}

interface Cursor {
  page: PDFPage;
  y: number;
}

export async function generateFitAssessmentPdf(
  form: FitFormData,
  result: FitResult
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  pdfDoc.setTitle(`Fit Assessment Report - ${sanitizeText(form.name) || form.email}`);
  pdfDoc.setAuthor("Executive Partners");

  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const italic = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

  let c: Cursor = newPage(pdfDoc);
  drawHeader(c, bold, regular, form, result);

  c.y -= 10;
  c = ensureSpace(pdfDoc, c, 100, bold, form);
  drawSectionTitle(c, bold, "Positioning");
  c.y -= 16;
  c = drawParagraph(c, regular, result.positioning, 10, DARK_TEXT, 14);
  c.y -= 8;
  c = ensureSpace(pdfDoc, c, 60, bold, form);
  c = drawParagraph(c, regular, result.commercialSummary, 10, DARK_TEXT, 14);
  c.y -= 16;

  c = ensureSpace(pdfDoc, c, 60, bold, form);
  drawSectionTitle(c, bold, "Top Markets");
  c.y -= 16;
  for (const m of result.topMarkets || []) {
    c = ensureSpace(pdfDoc, c, 70, bold, form);
    c = drawMarket(c, bold, regular, m);
    c.y -= 10;
  }

  if (result.matchedMandates && result.matchedMandates.length > 0) {
    c = ensureSpace(pdfDoc, c, 70, bold, form);
    drawSectionTitle(c, bold, "Live Mandates Matching Your Profile");
    c.y -= 16;
    for (const m of result.matchedMandates) {
      c = ensureSpace(pdfDoc, c, 35, bold, form);
      c = drawMandate(c, bold, regular, m);
    }
    c.y -= 8;
  }

  c = ensureSpace(pdfDoc, c, 80, bold, form);
  drawSectionTitle(c, bold, "What Opens Doors");
  c.y -= 16;
  for (const s of result.strengths || []) {
    c = ensureSpace(pdfDoc, c, 30, bold, form);
    c = drawBullet(c, regular, s, GOLD);
  }
  c.y -= 8;

  c = ensureSpace(pdfDoc, c, 80, bold, form);
  drawSectionTitle(c, bold, "What Limits Options");
  c.y -= 16;
  for (const g of result.gaps || []) {
    c = ensureSpace(pdfDoc, c, 30, bold, form);
    c = drawBullet(c, regular, g, GREY_TEXT);
  }
  c.y -= 8;

  if (result.legalNote) {
    c = ensureSpace(pdfDoc, c, 60, bold, form);
    drawSectionTitle(c, bold, "Legal Note");
    c.y -= 16;
    c = drawParagraph(c, regular, result.legalNote, 10, DARK_TEXT, 14);
    c.y -= 12;
  }
  if (result.timingNote) {
    c = ensureSpace(pdfDoc, c, 60, bold, form);
    drawSectionTitle(c, bold, "Timing");
    c.y -= 16;
    c = drawParagraph(c, regular, result.timingNote, 10, DARK_TEXT, 14);
    c.y -= 12;
  }

  c = ensureSpace(pdfDoc, c, 90, bold, form);
  drawSectionTitle(c, bold, "Executive Partners Assessment");
  c.y -= 16;
  c = drawParagraph(c, regular, result.epAssessment, 10, DARK_TEXT, 14);

  c = ensureSpace(pdfDoc, c, 60, bold, form);
  c.y -= 14;
  drawDivider(c);
  c.y -= 14;
  c = drawParagraph(
    c,
    italic,
    "This report has been generated by Executive Partners as part of the Private Bank Fit Assessment process. It supports a confidential career conversation with our team and is not a guarantee of placement or representation of any specific mandate.",
    8.5,
    GREY_TEXT,
    12
  );

  addFooters(pdfDoc, regular);

  const bytes = await pdfDoc.save();
  return Buffer.from(bytes);
}

function newPage(pdfDoc: PDFDocument): Cursor {
  const page = pdfDoc.addPage([PAGE_W, PAGE_H]);
  return { page, y: PAGE_H - MARGIN };
}

function ensureSpace(
  pdfDoc: PDFDocument,
  c: Cursor,
  needed: number,
  bold: PDFFont,
  form: FitFormData
): Cursor {
  if (c.y - needed < MARGIN + 40) {
    const next = newPage(pdfDoc);
    runningHeader(next, bold, form);
    return next;
  }
  return c;
}

function runningHeader(c: Cursor, bold: PDFFont, form: FitFormData) {
  c.page.drawText("EXECUTIVE PARTNERS", { x: MARGIN, y: c.y, size: 9, font: bold, color: NAVY });
  const label = sanitizeText(form.name) || form.email;
  c.page.drawText(label, {
    x: PAGE_W - MARGIN - bold.widthOfTextAtSize(label, 9),
    y: c.y, size: 9, font: bold, color: GREY_TEXT,
  });
  c.y -= 6;
  c.page.drawLine({ start: { x: MARGIN, y: c.y }, end: { x: PAGE_W - MARGIN, y: c.y }, thickness: 1.2, color: GOLD });
  c.y -= 18;
}

function drawHeader(c: Cursor, bold: PDFFont, regular: PDFFont, form: FitFormData, result: FitResult) {
  c.page.drawRectangle({ x: 0, y: PAGE_H - 70, width: PAGE_W, height: 70, color: NAVY });
  c.page.drawText("EXECUTIVE PARTNERS", { x: MARGIN, y: PAGE_H - 42, size: 18, font: bold, color: rgb(1, 1, 1) });
  c.page.drawText("Private Banking & Wealth Management Search", { x: MARGIN, y: PAGE_H - 58, size: 9, font: regular, color: GOLD });

  c.y = PAGE_H - 70 - 36;
  c.page.drawText("Private Bank Fit Assessment", { x: MARGIN, y: c.y, size: 16, font: bold, color: NAVY });
  c.y -= 22;

  const meta = [
    `Candidate: ${sanitizeText(form.name) || form.email}`,
    `Date: ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}`,
    `Overall fit: ${sanitizeText(result.overallFit)}`,
  ];
  for (const line of meta) {
    c.page.drawText(line, { x: MARGIN, y: c.y, size: 10, font: regular, color: DARK_TEXT });
    c.y -= 14;
  }

  c.y -= 6;
  c.page.drawRectangle({ x: MARGIN, y: c.y - 4, width: 4, height: 14, color: GOLD });
  c.page.drawText(sanitizeText(result.headline), { x: MARGIN + 10, y: c.y, size: 12.5, font: bold, color: NAVY });
  c.y -= 24;
  drawDivider(c);
}

function drawDivider(c: Cursor) {
  c.page.drawLine({ start: { x: MARGIN, y: c.y }, end: { x: PAGE_W - MARGIN, y: c.y }, thickness: 0.75, color: LIGHT_LINE });
}

function drawSectionTitle(c: Cursor, bold: PDFFont, title: string) {
  c.page.drawRectangle({ x: MARGIN, y: c.y - 4, width: 4, height: 14, color: GOLD });
  c.page.drawText(title, { x: MARGIN + 10, y: c.y, size: 12.5, font: bold, color: NAVY });
}

function drawMandate(c: Cursor, bold: PDFFont, regular: PDFFont, m: MatchedMandate): Cursor {
  const title = sanitizeText(m.title);
  const subtitle = sanitizeText(m.subtitle);
  const location = sanitizeText(m.location);
  const aum = sanitizeText(m.aum);
  const marketLine = subtitle ? `${subtitle}  -  booked in ${location}` : location;
  const meta = [marketLine, aum].filter(Boolean).join("  -  ");
  c.page.drawText(title, { x: MARGIN, y: c.y, size: 10, font: bold, color: NAVY });
  c.y -= 13;
  if (meta) {
    c.page.drawText(meta, { x: MARGIN, y: c.y, size: 9, font: regular, color: GREY_TEXT });
    c.y -= 13;
  }
  c.y -= 4;
  return c;
}

function drawMarket(c: Cursor, bold: PDFFont, regular: PDFFont, m: TopMarket): Cursor {
  const title = sanitizeText(`${m.city}  -  ${m.fitLevel} fit`);
  c.page.drawText(title, { x: MARGIN, y: c.y, size: 10.5, font: bold, color: NAVY });
  c.y -= 14;
  let cur = drawParagraph(c, regular, m.rationale, 9.5, DARK_TEXT, 13);
  if (m.hiringContext) {
    cur.y -= 2;
    cur = drawParagraph(cur, regular, `2026 context: ${m.hiringContext}`, 9, GREY_TEXT, 12);
  }
  if (m.keyRequirement) {
    cur.y -= 2;
    cur = drawParagraph(cur, regular, `Key requirement: ${m.keyRequirement}`, 9, GREY_TEXT, 12);
  }
  return cur;
}

function drawBullet(c: Cursor, regular: PDFFont, text: string, dotColor: ReturnType<typeof rgb>): Cursor {
  c.page.drawCircle({ x: MARGIN + 3, y: c.y + 3, size: 2, color: dotColor });
  const clean = sanitizeText(text);
  const words = clean.split(/\s+/);
  let line = "";
  let y = c.y;
  const x0 = MARGIN + 12;
  const w = CONTENT_W - 12;
  const flush = () => {
    if (!line) return;
    c.page.drawText(line, { x: x0, y, size: 9.5, font: regular, color: DARK_TEXT });
    y -= 13;
  };
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (regular.widthOfTextAtSize(test, 9.5) > w) { flush(); line = word; } else { line = test; }
  }
  flush();
  return { page: c.page, y: y - 4 };
}

function drawParagraph(
  c: Cursor, font: PDFFont, text: string, size: number, color: ReturnType<typeof rgb>, lineHeight: number
): Cursor {
  const clean = sanitizeText(text);
  const words = clean.split(/\s+/);
  let line = "";
  let y = c.y;
  const flush = () => {
    if (!line) return;
    c.page.drawText(line, { x: MARGIN, y, size, font, color });
    y -= lineHeight;
  };
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(test, size) > CONTENT_W) { flush(); line = word; } else { line = test; }
  }
  flush();
  return { page: c.page, y };
}

function addFooters(pdfDoc: PDFDocument, regular: PDFFont) {
  const pages = pdfDoc.getPages();
  pages.forEach((page, i) => {
    const text = `Executive Partners  -  execpartners.ch  -  Page ${i + 1} of ${pages.length}`;
    const w = regular.widthOfTextAtSize(text, 8);
    page.drawText(text, { x: (PAGE_W - w) / 2, y: 24, size: 8, font: regular, color: GREY_TEXT });
  });
}
